"use strict";
(() => {
const FS=1600,N=2048,WIN=1600,HOP=800,MINF=15,MAXF=700,MAX=FS*300;
const V={phase:"idle",pending:null,baseline:[],run:[],validation:[],profile:null,analysis:null,lastSeq:null,gaps:0,clipped:0,tempApplied:false};
const host=document.querySelector("#vibrationView"),section=document.createElement("section");
section.className="card vib-card";
section.innerHTML=`<div class="vib-head"><div><h2>振动分析向导</h2><p>采集原始 IMU → 1 秒窗频谱 → 自动生成滤波建议 → 离线重放 → 实机复测</p></div><button id="vibExport" disabled>导出报告</button></div>
<div class="vib-steps"><div class="vib-step" data-step="baseline"><b>1 · 电机关闭基线</b><span id="vibBaseCount">等待采集</span></div><div class="vib-step" data-step="run"><b>2 · 实际工况</b><span id="vibRunCount">等待采集</span></div><div class="vib-step" data-step="validation"><b>3 · 上机复测</b><span id="vibValCount">分析后可用</span></div></div>
<div class="vib-actions"><button class="primary" id="vibBase">开始基线</button><button id="vibRun">开始工况</button><button id="vibStop" disabled>停止采集</button><button id="vibAnalyze" disabled>生成滤波方案</button><button id="vibApply" disabled>临时应用到设备</button><button id="vibSave" disabled>保存到 Flash</button><button id="vibValidate" disabled>开始复测</button><button id="vibFilterReset">关闭设备滤波</button><button id="vibReset">清空分析</button></div>
<div class="vib-status" id="vibStatus">请先连接 IMU，保持电机关闭并采集至少 3 秒。</div>
<div class="vib-grid"><div class="vib-plot"><canvas id="vibChart"></canvas></div><div class="vib-results" id="vibResults"><h3>分析结果</h3><div class="vib-note">振动模式采集 1600 Hz 未平均原始数据，分析范围 15–700 Hz。已经削顶或进入传感器前混叠的数据无法恢复。</div></div></div>`;
host.appendChild(section);
const $=id=>document.getElementById(id),status=$("vibStatus"),results=$("vibResults"),canvas=$("vibChart"),ctx=canvas.getContext("2d");
const B={baseline:$("vibBase"),run:$("vibRun"),stop:$("vibStop"),analyze:$("vibAnalyze"),apply:$("vibApply"),save:$("vibSave"),validation:$("vibValidate"),filterReset:$("vibFilterReset"),reset:$("vibReset"),export:$("vibExport")};
const secs=a=>(a.length/FS).toFixed(1);
function update(){
  $("vibBaseCount").textContent=`${secs(V.baseline)} 秒 · ${V.baseline.length} 样本`;
  $("vibRunCount").textContent=`${secs(V.run)} 秒 · ${V.run.length} 样本`;
  $("vibValCount").textContent=`${secs(V.validation)} 秒 · ${V.validation.length} 样本`;
  document.querySelectorAll(".vib-step").forEach(x=>{const k=x.dataset.step;x.classList.toggle("active",V.phase===k);x.classList.toggle("done",V[k].length>=FS*3)});
  B.stop.disabled=V.phase==="idle";B.analyze.disabled=V.phase!=="idle"||V.baseline.length<FS*3||V.run.length<FS*3;B.apply.disabled=!V.profile||V.phase!=="idle";B.save.disabled=!V.tempApplied;B.validation.disabled=!V.tempApplied||V.phase!=="idle";B.export.disabled=!V.analysis;
}
function activate(phase){if(phase==="validation")V.validation=[];V.phase=phase;V.pending=null;V.lastSeq=null;V.gaps=V.clipped=0;status.textContent=phase==="baseline"?"正在以 1600 Hz 采集电机关闭基线；建议 5–10 秒。":phase==="run"?"正在以 1600 Hz 采集实际工况；请覆盖常用转速、负载和运动状态。":"正在以 1600 Hz 上机复测；请重复与工况采集相同的条件。";update()}
function begin(phase){if(typeof state!=="undefined"&&!state.connected){status.textContent="请先连接 IMU。";return}if(typeof sendCommand==="function"){V.pending=phase;status.textContent="正在请求设备进入 1600 Hz 原始振动模式…";sendCommand(0x08)}else activate(phase)}
function finish(p){status.textContent=`已停止${p==="baseline"?"基线":p==="run"?"工况":"复测"}采集。序号缺口 ${V.gaps}，近满量程样本 ${V.clipped}。`;if(p==="validation"&&V.profile)renderValidation();update()}
function stop(){const p=V.phase;if(p==="idle")return;V.phase="idle";V.pending=p;if(typeof sendCommand==="function"){status.textContent="正在退出振动采集模式…";sendCommand(0x09)}else{V.pending=null;finish(p)}update()}
window.vibrationAddSample=raw=>{if(V.phase==="idle")return;const a=V[V.phase];if(a.length>=MAX){stop();return}if(V.lastSeq!==null&&((raw.seq-V.lastSeq)&65535)!==1)V.gaps++;V.lastSeq=raw.seq;if(raw.acc.some(x=>Math.abs(x)>=2028)||raw.gyr.some(x=>Math.abs(x)>=32440))V.clipped++;a.push({a:raw.acc.map(x=>x/2048),g:raw.gyr.map(x=>x/16.4),seq:raw.seq});if((a.length&127)===0)update()};
function fft(re,im){for(let i=1,j=0;i<N;i++){let bit=N>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=N;len<<=1){const ang=-2*Math.PI/len;for(let i=0;i<N;i+=len)for(let j=0;j<len/2;j++){const c=Math.cos(ang*j),s=Math.sin(ang*j),u=re[i+j],v=im[i+j],tr=re[i+j+len/2]*c-im[i+j+len/2]*s,ti=re[i+j+len/2]*s+im[i+j+len/2]*c;re[i+j]=u+tr;im[i+j]=v+ti;re[i+j+len/2]=u-tr;im[i+j+len/2]=v-ti}}}
function spectrum(samples,key){const bins=N/2+1,sum=new Float64Array(bins),persist=new Uint16Array(bins);let windows=0;for(let start=0;start+WIN<=samples.length;start+=HOP){const wp=new Float64Array(bins);for(let axis=0;axis<3;axis++){const re=new Float64Array(N),im=new Float64Array(N);let mean=0;for(let i=0;i<WIN;i++)mean+=samples[start+i][key][axis];mean/=WIN;for(let i=0;i<WIN;i++)re[i]=(samples[start+i][key][axis]-mean)*(0.5-0.5*Math.cos(2*Math.PI*i/(WIN-1)));fft(re,im);for(let k=0;k<bins;k++)wp[k]+=(re[k]*re[k]+im[k]*im[k])/(WIN*WIN)}for(let k=0;k<bins;k++)sum[k]+=wp[k];let avg=0,n=0;for(let k=Math.ceil(MINF*N/FS);k<=Math.floor(MAXF*N/FS);k++){avg+=wp[k];n++}avg/=n;for(let k=2;k<bins-2;k++)if(wp[k]>avg*4&&wp[k]>=wp[k-1]&&wp[k]>=wp[k+1])persist[k]++;windows++}for(let k=0;k<bins;k++)sum[k]/=Math.max(1,windows);return{power:Array.from(sum),persist:Array.from(persist),windows}}
function peaks(run,base,type){const lo=Math.ceil(MINF*N/FS),hi=Math.floor(MAXF*N/FS),c=[];for(let k=lo+2;k<hi-2;k++){const e=Math.max(0,run.power[k]-base.power[k]);if(e<=0||e<Math.max(run.power[k-1]-base.power[k-1],run.power[k+1]-base.power[k+1]))continue;const ratio=run.power[k]/Math.max(base.power[k],1e-14),p=run.persist[k]/Math.max(1,run.windows);if(ratio>=2&&p>=.2)c.push({type,k,hz:k*FS/N,score:e*Math.log2(ratio+1)*(.5+p),ratio,persist:p,excess:e})}c.sort((a,b)=>b.score-a.score);const out=[];for(const p of c){if(out.every(q=>Math.abs(q.hz-p.hz)>=10)){let l=p.k,r=p.k,half=p.excess/2;while(l>lo&&Math.max(0,run.power[l]-base.power[l])>half)l--;while(r<hi&&Math.max(0,run.power[r]-base.power[r])>half)r++;p.q=Math.max(3,Math.min(30,p.hz/Math.max(FS/N,(r-l)*FS/N)));out.push(p);if(out.length===3)break}}return out}
function biquad(type,f,q=.707){const w=2*Math.PI*f/FS,c=Math.cos(w),s=Math.sin(w),alpha=s/(2*q),a0=1+alpha,a1=-2*c,a2=1-alpha;let b0,b1,b2;if(type==="notch"){b0=1;b1=-2*c;b2=1}else{b0=(1-c)/2;b1=1-c;b2=(1-c)/2}return[b0/a0,b1/a0,b2/a0,a1/a0,a2/a0]}
function filterAxis(x,stages){let y=x.slice();for(const co of stages){const[b0,b1,b2,a1,a2]=co;let x1=0,x2=0,y1=0,y2=0;y=y.map(x0=>{const o=b0*x0+b1*x1+b2*x2-a1*y1-a2*y2;x2=x1;x1=x0;y2=y1;y1=o;return o})}return y}
function hfRms(samples,key,profile){const stages=(profile||[]).filter(p=>p.type===key).map(p=>biquad("notch",p.hz,p.q));if(profile&&profile.lowpass)stages.push(biquad("lowpass",profile.lowpass));let total=0,n=0;for(let axis=0;axis<3;axis++){const y=filterAxis(samples.map(s=>s[key][axis]),stages);for(let i=1;i<y.length;i++){const d=y[i]-y[i-1];total+=d*d;n++}}return Math.sqrt(total/Math.max(1,n))}
function analyze(){status.textContent="正在执行 1 秒窗 FFT 和离线因果滤波重放…";setTimeout(()=>{const ba=spectrum(V.baseline,"a"),bg=spectrum(V.baseline,"g"),ra=spectrum(V.run,"a"),rg=spectrum(V.run,"g"),all=[...peaks(ra,ba,"a"),...peaks(rg,bg,"g")].sort((a,b)=>b.score-a.score),profile=[];for(const p of all)if(profile.every(q=>q.type!==p.type||Math.abs(q.hz-p.hz)>=10)){profile.push(p);if(profile.length===6)break}const highest=profile.reduce((m,p)=>Math.max(m,p.hz),0);profile.lowpass=highest?Math.min(600,Math.max(120,Math.round((highest+80)/10)*10)):200;V.profile=profile;V.analysis={ba,bg,ra,rg,before:{a:hfRms(V.run,"a"),g:hfRms(V.run,"g")},after:{a:hfRms(V.run,"a",profile),g:hfRms(V.run,"g",profile)},created:new Date().toISOString(),sampleRate:FS};renderResults();drawSpectrum();status.textContent=profile.length?`找到 ${profile.length} 个重复振动峰并完成离线重放。请检查建议，再临时应用到设备并复测。`:"未找到稳定且明显高于基线的窄带峰；请延长采集或扩大转速范围。";update()},20)}
function renderResults(){const A=V.analysis,p=V.profile,rows=p.map((x,i)=>`<tr><td><label><input class="vib-notch-on" data-i="${i}" type="checkbox" checked> ${x.type==="a"?"加速度":"陀螺仪"}</label></td><td><input class="vib-hz" data-i="${i}" type="number" min="10" max="700" step="0.1" value="${x.hz.toFixed(1)}"> Hz</td><td><input class="vib-q" data-i="${i}" type="number" min="2" max="50" step="0.1" value="${x.q.toFixed(1)}"></td><td>${x.ratio.toFixed(1)}×</td><td>${Math.round(x.persist*100)}%</td></tr>`).join("");results.innerHTML=`<h3>建议滤波方案（可编辑）</h3><table class="vib-table"><tr><th>传感器</th><th>中心</th><th>Q</th><th>基线比</th><th>窗口出现</th></tr>${rows||'<tr><td colspan="5">无可靠窄带峰</td></tr>'}</table><div class="vib-metric"><span>常规输出频率</span><select id="vibOutputRate"><option>1600</option><option selected>800</option><option>400</option><option>200</option></select></div><div class="vib-metric"><span>串口波特率</span><select id="vibBaud"><option selected>460800</option><option>2000000</option></select></div><div class="vib-note">1600 Hz 必须选择 2000000；所有频率都输出原始帧和姿态帧。800/400/200 Hz 的原始值分别按连续 2/4/8 个 1600 Hz 样本分组平均。</div><div class="vib-metric"><label><input id="vibAccLpfOn" type="checkbox" checked> 加速度低通</label><span><input id="vibAccLpf" type="number" min="5" max="600" value="${p.lowpass}"> Hz</span></div><div class="vib-metric"><label><input id="vibGyrLpfOn" type="checkbox" checked> 陀螺仪低通</label><span><input id="vibGyrLpf" type="number" min="5" max="600" value="${p.lowpass}"> Hz</span></div><div class="vib-metric"><span>加速度高频 RMS</span><b>${A.before.a.toFixed(4)} → ${A.after.a.toFixed(4)} g/sample</b></div><div class="vib-metric"><span>陀螺仪高频 RMS</span><b>${A.before.g.toFixed(3)} → ${A.after.g.toFixed(3)} °/s/sample</b></div><div class="vib-note">先“临时应用到设备”，参数只在 RAM 生效；同工况复测确认后再“保存 Flash”。原始串口数据始终不滤波。</div>`;$("vibOutputRate").onchange=()=>{if(+$("vibOutputRate").value===1600)$("vibBaud").value="2000000"}}
function drawSpectrum(){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect(),w=Math.max(300,r.width),h=290;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);const x0=42,x1=w-12,y0=18,y1=h-28,A=V.analysis,span=MAXF-MINF;let mx=1e-12;for(let k=Math.ceil(MINF*N/FS);k<=Math.floor(MAXF*N/FS);k++)mx=Math.max(mx,A.ra.power[k],A.rg.power[k]);const draw=(arr,color)=>{ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();let first=true;for(let k=Math.ceil(MINF*N/FS);k<=Math.floor(MAXF*N/FS);k++){const x=x0+(x1-x0)*(k*FS/N-MINF)/span,y=y1-(y1-y0)*Math.log10(1+99*arr[k]/mx)/2;if(first){ctx.moveTo(x,y);first=false}else ctx.lineTo(x,y)}ctx.stroke()};ctx.strokeStyle="#e5e7eb";ctx.fillStyle="#64748b";ctx.font="10px sans-serif";for(let f=100;f<=700;f+=100){const x=x0+(x1-x0)*(f-MINF)/span;ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y1);ctx.stroke();ctx.fillText(f+" Hz",x-14,y1+16)}draw(A.ra.power,"#ef4444");draw(A.rg.power,"#2563eb");for(const p of V.profile){const x=x0+(x1-x0)*(p.hz-MINF)/span;ctx.strokeStyle=p.type==="a"?"#ef4444":"#2563eb";ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y1);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle="#ef4444";ctx.fillText("Accel",x0,12);ctx.fillStyle="#2563eb";ctx.fillText("Gyro",x0+45,12)}
function renderValidation(){if(V.validation.length<FS*3){status.textContent="复测少于 3 秒，数据不足。";return}const raw={a:hfRms(V.validation,"a"),g:hfRms(V.validation,"g")},filtered={a:hfRms(V.validation,"a",V.profile),g:hfRms(V.validation,"g",V.profile)},A=V.analysis;results.insertAdjacentHTML("beforeend",`<h3 style="margin-top:16px">上机复测</h3><div class="vib-metric"><span>原始加速度，相对初测</span><b class="${raw.a<A.before.a?'vib-good':'vib-warn'}">${raw.a.toFixed(4)} (${(100*raw.a/A.before.a).toFixed(0)}%)</b></div><div class="vib-metric"><span>原始陀螺仪，相对初测</span><b class="${raw.g<A.before.g?'vib-good':'vib-warn'}">${raw.g.toFixed(3)} (${(100*raw.g/A.before.g).toFixed(0)}%)</b></div><div class="vib-metric"><span>复测数据模拟滤波后</span><b>${filtered.a.toFixed(4)} g / ${filtered.g.toFixed(3)} °/s</b></div>`);V.analysis.validation={raw,filtered,samples:V.validation.length};status.textContent="复测分析完成。请比较同转速、同负载下的结果。";update()}
function filterPayload(){const buf=new ArrayBuffer(68),dv=new DataView(buf);let flags=0,off=12;const accHz=[100,150,200],accQ=[10,10,10],gyrHz=[100,150,200],gyrQ=[10,10,10];if($("vibAccLpfOn")?.checked)flags|=1;if($("vibGyrLpfOn")?.checked)flags|=2;document.querySelectorAll(".vib-notch-on").forEach(el=>{const i=+el.dataset.i,p=V.profile[i],hz=+document.querySelector(`.vib-hz[data-i="${i}"]`).value,q=+document.querySelector(`.vib-q[data-i="${i}"]`).value,slot=V.profile.slice(0,i).filter(x=>x.type===p.type).length;if(slot<3){if(p.type==="a"){accHz[slot]=hz;accQ[slot]=q;if(el.checked)flags|=1<<(2+slot)}else{gyrHz[slot]=hz;gyrQ[slot]=q;if(el.checked)flags|=1<<(5+slot)}}});dv.setUint32(0,flags,true);dv.setUint32(4,+$("vibOutputRate").value,true);dv.setUint32(8,+$("vibBaud").value,true);const vals=[+$("vibAccLpf").value,+$("vibGyrLpf").value,...accHz,...accQ,...gyrHz,...gyrQ];for(const v of vals){dv.setFloat32(off,v,true);off+=4}return new Uint8Array(buf)}
function applyDevice(){if(typeof sendCommand!=="function")return;const rate=+$("vibOutputRate").value,baud=+$("vibBaud").value;if(rate===1600&&baud<2000000){status.textContent="1600 Hz 必须使用 2000000 波特率。";return}V.requestedBaud=baud;V.requestedRate=rate;V.tempApplied=false;status.textContent="正在把滤波和传输参数临时应用到设备 RAM…";sendCommand(0x05,filterPayload());update()}
function saveDevice(){if(typeof sendCommand!=="function")return;status.textContent="正在保存已验证的滤波参数到 Flash…";sendCommand(0x06)}
function resetDevice(){if(typeof sendCommand!=="function")return;status.textContent="正在关闭设备的全部软件滤波…";sendCommand(0x07)}
window.vibrationHandleReply=(cmd,ok,payload)=>{
  if(cmd===0x08){if(ok&&V.pending)activate(V.pending);else{V.pending=null;status.textContent="设备不支持 1600 Hz 振动模式，请先升级固件。"}}
  else if(cmd===0x09){const p=V.pending;V.pending=null;if(ok&&p)finish(p);else status.textContent="退出振动模式失败，请重新连接设备。"}
  else if(cmd===0x05){V.tempApplied=ok;status.textContent=ok?"滤波和传输参数已临时应用到 RAM。请在相同工况下开始复测；确认后再保存 Flash。":"设备拒绝参数：请检查输出频率、波特率、滤波频率和 Q。";if(ok&&V.requestedRate&&typeof els!=="undefined"){window.currentOutputRate=V.requestedRate;els.targetFrequency.textContent=`/ ${V.requestedRate} Hz`;}if(ok&&V.requestedBaud&&typeof reconnectBaud==="function"&&+els.baudRate.value!==V.requestedBaud)reconnectBaud(V.requestedBaud);update()}
  else if(cmd===0x06){status.textContent=ok?"滤波参数已保存到 Flash，重启后仍会生效。":"保存 Flash 失败，RAM 参数仍在当前会话生效。"}
  else if(cmd===0x07){V.tempApplied=false;status.textContent=ok?"设备滤波已关闭（当前为 RAM 状态，保存后才会持久化）。":"关闭设备滤波失败。";update()}
  else if(cmd===0x04&&ok&&payload.length===68){const d=new DataView(payload.buffer,payload.byteOffset,payload.byteLength),rate=d.getUint32(4,true),baud=d.getUint32(8,true);window.currentOutputRate=rate;els.targetFrequency.textContent=`/ ${rate} Hz`;els.baudRate.value=String(baud);status.textContent=`设备当前：${rate} Hz，${baud} baud，滤波${d.getUint32(0,true)?"已启用":"关闭"}。`}
};
window.vibrationGetConfig=()=>{if(typeof sendCommand==="function")sendCommand(0x04)};
function reset(){if(V.phase!=="idle"&&typeof sendCommand==="function")sendCommand(0x09);Object.assign(V,{phase:"idle",pending:null,baseline:[],run:[],validation:[],profile:null,analysis:null,lastSeq:null,gaps:0,clipped:0,tempApplied:false});results.innerHTML='<h3>分析结果</h3><div class="vib-note">振动模式采集 1600 Hz 未平均原始数据，分析范围 15–700 Hz。</div>';ctx.clearRect(0,0,canvas.width,canvas.height);status.textContent="请先连接 IMU，保持电机关闭并采集至少 3 秒。";update()}
function exportReport(){const payload={format:"CJ02-vibration-profile-v1",analysis:V.analysis,profile:{notches:Array.from(V.profile),lowpassHz:V.profile.lowpass},captures:{baselineSamples:V.baseline.length,runSamples:V.run.length,validationSamples:V.validation.length,gaps:V.gaps,nearClipping:V.clipped}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`cj02-vibration-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
B.baseline.onclick=()=>begin("baseline");B.run.onclick=()=>begin("run");B.stop.onclick=stop;B.analyze.onclick=analyze;B.apply.onclick=applyDevice;B.save.onclick=saveDevice;B.validation.onclick=()=>begin("validation");B.filterReset.onclick=resetDevice;B.reset.onclick=reset;B.export.onclick=exportReport;update();
})();
