"use strict";
(() => {
const FS=800,N=1024,WIN=800,HOP=400,MAX=FS*300;
const V={phase:"idle",baseline:[],run:[],validation:[],profile:null,analysis:null,lastSeq:null,gaps:0,clipped:0};
const host=document.querySelector(".hint"),section=document.createElement("section");
section.className="card vib-card";
section.innerHTML=`<div class="vib-head"><div><h2>振动分析向导</h2><p>采集原始 IMU → 1 秒窗频谱 → 自动生成滤波建议 → 离线重放 → 实机复测</p></div><button id="vibExport" disabled>导出报告</button></div>
<div class="vib-steps"><div class="vib-step" data-step="baseline"><b>1 · 电机关闭基线</b><span id="vibBaseCount">等待采集</span></div><div class="vib-step" data-step="run"><b>2 · 实际工况</b><span id="vibRunCount">等待采集</span></div><div class="vib-step" data-step="validation"><b>3 · 上机复测</b><span id="vibValCount">分析后可用</span></div></div>
<div class="vib-actions"><button class="primary" id="vibBase">开始基线</button><button id="vibRun">开始工况</button><button id="vibStop" disabled>停止采集</button><button id="vibAnalyze" disabled>生成滤波方案</button><button id="vibValidate" disabled>开始复测</button><button id="vibReset">清空</button></div>
<div class="vib-status" id="vibStatus">请先连接 IMU，保持电机关闭并采集至少 3 秒。</div>
<div class="vib-grid"><div class="vib-plot"><canvas id="vibChart"></canvas></div><div class="vib-results" id="vibResults"><h3>分析结果</h3><div class="vib-note">分析范围 15–350 Hz。串口帧是 1600 Hz 相邻样本平均后的 800 Hz 数据，无法恢复已经削顶或混叠的振动。</div></div></div>`;
host.parentNode.insertBefore(section,host);
const $=id=>document.getElementById(id),status=$("vibStatus"),results=$("vibResults"),canvas=$("vibChart"),ctx=canvas.getContext("2d");
const B={baseline:$("vibBase"),run:$("vibRun"),stop:$("vibStop"),analyze:$("vibAnalyze"),validation:$("vibValidate"),reset:$("vibReset"),export:$("vibExport")};
const secs=a=>(a.length/FS).toFixed(1);
function update(){
  $("vibBaseCount").textContent=`${secs(V.baseline)} 秒 · ${V.baseline.length} 样本`;
  $("vibRunCount").textContent=`${secs(V.run)} 秒 · ${V.run.length} 样本`;
  $("vibValCount").textContent=`${secs(V.validation)} 秒 · ${V.validation.length} 样本`;
  document.querySelectorAll(".vib-step").forEach(x=>{const k=x.dataset.step;x.classList.toggle("active",V.phase===k);x.classList.toggle("done",V[k].length>=FS*3)});
  B.stop.disabled=V.phase==="idle";B.analyze.disabled=V.phase!=="idle"||V.baseline.length<FS*3||V.run.length<FS*3;B.validation.disabled=!V.profile||V.phase!=="idle";B.export.disabled=!V.analysis;
}
function begin(phase){if(typeof state!=="undefined"&&!state.connected){status.textContent="请先连接 IMU。";return}if(phase==="validation")V.validation=[];V.phase=phase;V.lastSeq=null;V.gaps=V.clipped=0;status.textContent=phase==="baseline"?"正在采集电机关闭基线；建议 5–10 秒。":phase==="run"?"正在采集实际工况；请覆盖常用转速、负载和运动状态。":"正在上机复测；请重复与工况采集相同的条件。";update()}
function stop(){const p=V.phase;if(p==="idle")return;V.phase="idle";status.textContent=`已停止${p==="baseline"?"基线":p==="run"?"工况":"复测"}采集。序号缺口 ${V.gaps}，近满量程样本 ${V.clipped}。`;if(p==="validation"&&V.profile)renderValidation();update()}
window.vibrationAddSample=raw=>{if(V.phase==="idle")return;const a=V[V.phase];if(a.length>=MAX){stop();return}if(V.lastSeq!==null&&((raw.seq-V.lastSeq)&65535)!==1)V.gaps++;V.lastSeq=raw.seq;if(raw.acc.some(x=>Math.abs(x)>=2028)||raw.gyr.some(x=>Math.abs(x)>=32440))V.clipped++;a.push({a:raw.acc.map(x=>x/2048),g:raw.gyr.map(x=>x/16.4),seq:raw.seq});if((a.length&127)===0)update()};
function fft(re,im){for(let i=1,j=0;i<N;i++){let bit=N>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=N;len<<=1){const ang=-2*Math.PI/len;for(let i=0;i<N;i+=len)for(let j=0;j<len/2;j++){const c=Math.cos(ang*j),s=Math.sin(ang*j),u=re[i+j],v=im[i+j],tr=re[i+j+len/2]*c-im[i+j+len/2]*s,ti=re[i+j+len/2]*s+im[i+j+len/2]*c;re[i+j]=u+tr;im[i+j]=v+ti;re[i+j+len/2]=u-tr;im[i+j+len/2]=v-ti}}}
function spectrum(samples,key){const bins=N/2+1,sum=new Float64Array(bins),persist=new Uint16Array(bins);let windows=0;for(let start=0;start+WIN<=samples.length;start+=HOP){const wp=new Float64Array(bins);for(let axis=0;axis<3;axis++){const re=new Float64Array(N),im=new Float64Array(N);let mean=0;for(let i=0;i<WIN;i++)mean+=samples[start+i][key][axis];mean/=WIN;for(let i=0;i<WIN;i++)re[i]=(samples[start+i][key][axis]-mean)*(0.5-0.5*Math.cos(2*Math.PI*i/(WIN-1)));fft(re,im);for(let k=0;k<bins;k++)wp[k]+=(re[k]*re[k]+im[k]*im[k])/(WIN*WIN)}for(let k=0;k<bins;k++)sum[k]+=wp[k];let avg=0,n=0;for(let k=Math.ceil(15*N/FS);k<=Math.floor(350*N/FS);k++){avg+=wp[k];n++}avg/=n;for(let k=2;k<bins-2;k++)if(wp[k]>avg*4&&wp[k]>=wp[k-1]&&wp[k]>=wp[k+1])persist[k]++;windows++}for(let k=0;k<bins;k++)sum[k]/=Math.max(1,windows);return{power:Array.from(sum),persist:Array.from(persist),windows}}
function peaks(run,base,type){const lo=Math.ceil(15*N/FS),hi=Math.floor(350*N/FS),c=[];for(let k=lo+2;k<hi-2;k++){const e=Math.max(0,run.power[k]-base.power[k]);if(e<=0||e<Math.max(run.power[k-1]-base.power[k-1],run.power[k+1]-base.power[k+1]))continue;const ratio=run.power[k]/Math.max(base.power[k],1e-14),p=run.persist[k]/Math.max(1,run.windows);if(ratio>=2&&p>=.2)c.push({type,k,hz:k*FS/N,score:e*Math.log2(ratio+1)*(.5+p),ratio,persist:p,excess:e})}c.sort((a,b)=>b.score-a.score);const out=[];for(const p of c){if(out.every(q=>Math.abs(q.hz-p.hz)>=10)){let l=p.k,r=p.k,half=p.excess/2;while(l>lo&&Math.max(0,run.power[l]-base.power[l])>half)l--;while(r<hi&&Math.max(0,run.power[r]-base.power[r])>half)r++;p.q=Math.max(3,Math.min(30,p.hz/Math.max(FS/N,(r-l)*FS/N)));out.push(p);if(out.length===3)break}}return out}
function biquad(type,f,q=.707){const w=2*Math.PI*f/FS,c=Math.cos(w),s=Math.sin(w),alpha=s/(2*q),a0=1+alpha,a1=-2*c,a2=1-alpha;let b0,b1,b2;if(type==="notch"){b0=1;b1=-2*c;b2=1}else{b0=(1-c)/2;b1=1-c;b2=(1-c)/2}return[b0/a0,b1/a0,b2/a0,a1/a0,a2/a0]}
function filterAxis(x,stages){let y=x.slice();for(const co of stages){const[b0,b1,b2,a1,a2]=co;let x1=0,x2=0,y1=0,y2=0;y=y.map(x0=>{const o=b0*x0+b1*x1+b2*x2-a1*y1-a2*y2;x2=x1;x1=x0;y2=y1;y1=o;return o})}return y}
function hfRms(samples,key,profile){const stages=(profile||[]).filter(p=>p.type===key).map(p=>biquad("notch",p.hz,p.q));if(profile&&profile.lowpass)stages.push(biquad("lowpass",profile.lowpass));let total=0,n=0;for(let axis=0;axis<3;axis++){const y=filterAxis(samples.map(s=>s[key][axis]),stages);for(let i=1;i<y.length;i++){const d=y[i]-y[i-1];total+=d*d;n++}}return Math.sqrt(total/Math.max(1,n))}
function analyze(){status.textContent="正在执行 1 秒窗 FFT 和离线因果滤波重放…";setTimeout(()=>{const ba=spectrum(V.baseline,"a"),bg=spectrum(V.baseline,"g"),ra=spectrum(V.run,"a"),rg=spectrum(V.run,"g"),all=[...peaks(ra,ba,"a"),...peaks(rg,bg,"g")].sort((a,b)=>b.score-a.score),profile=[];for(const p of all)if(profile.every(q=>q.type!==p.type||Math.abs(q.hz-p.hz)>=10)){profile.push(p);if(profile.length===6)break}const highest=profile.reduce((m,p)=>Math.max(m,p.hz),0);profile.lowpass=highest?Math.min(350,Math.max(120,Math.round((highest+60)/10)*10)):200;V.profile=profile;V.analysis={ba,bg,ra,rg,before:{a:hfRms(V.run,"a"),g:hfRms(V.run,"g")},after:{a:hfRms(V.run,"a",profile),g:hfRms(V.run,"g",profile)},created:new Date().toISOString(),sampleRate:FS};renderResults();drawSpectrum();status.textContent=profile.length?`找到 ${profile.length} 个重复振动峰并完成离线重放。请检查建议，再进行同工况复测。`:"未找到稳定且明显高于基线的窄带峰；请延长采集或扩大转速范围。";update()},20)}
function renderResults(){const A=V.analysis,p=V.profile,rows=p.map(x=>`<tr><td>${x.type==="a"?"加速度":"陀螺仪"}</td><td>${x.hz.toFixed(1)} Hz</td><td>${x.q.toFixed(1)}</td><td>${x.ratio.toFixed(1)}×</td><td>${Math.round(x.persist*100)}%</td></tr>`).join("");results.innerHTML=`<h3>建议滤波方案</h3><table class="vib-table"><tr><th>传感器</th><th>中心</th><th>Q</th><th>基线比</th><th>窗口出现</th></tr>${rows||'<tr><td colspan="5">无可靠窄带峰</td></tr>'}</table><div class="vib-metric"><span>建议低通截止</span><b>${p.lowpass} Hz</b></div><div class="vib-metric"><span>加速度高频 RMS</span><b>${A.before.a.toFixed(4)} → ${A.after.a.toFixed(4)} g/sample</b></div><div class="vib-metric"><span>陀螺仪高频 RMS</span><b>${A.before.g.toFixed(3)} → ${A.after.g.toFixed(3)} °/s/sample</b></div><div class="vib-note">“之后”是同一段数据通过建议的因果二阶陷波与低通后重放的结果，不代表真实姿态一定改善。当前版本不会自动写入设备。</div>`}
function drawSpectrum(){const dpr=devicePixelRatio||1,r=canvas.getBoundingClientRect(),w=Math.max(300,r.width),h=290;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);const x0=42,x1=w-12,y0=18,y1=h-28,A=V.analysis;let mx=1e-12;for(let k=Math.ceil(15*N/FS);k<=Math.floor(350*N/FS);k++)mx=Math.max(mx,A.ra.power[k],A.rg.power[k]);const draw=(arr,color)=>{ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.beginPath();let first=true;for(let k=Math.ceil(15*N/FS);k<=Math.floor(350*N/FS);k++){const x=x0+(x1-x0)*(k*FS/N-15)/335,y=y1-(y1-y0)*Math.log10(1+99*arr[k]/mx)/2;if(first){ctx.moveTo(x,y);first=false}else ctx.lineTo(x,y)}ctx.stroke()};ctx.strokeStyle="#e5e7eb";ctx.fillStyle="#64748b";ctx.font="10px sans-serif";for(let f=50;f<=350;f+=50){const x=x0+(x1-x0)*(f-15)/335;ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y1);ctx.stroke();ctx.fillText(f+" Hz",x-12,y1+16)}draw(A.ra.power,"#ef4444");draw(A.rg.power,"#2563eb");for(const p of V.profile){const x=x0+(x1-x0)*(p.hz-15)/335;ctx.strokeStyle=p.type==="a"?"#ef4444":"#2563eb";ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(x,y0);ctx.lineTo(x,y1);ctx.stroke();ctx.setLineDash([])}ctx.fillStyle="#ef4444";ctx.fillText("Accel",x0,12);ctx.fillStyle="#2563eb";ctx.fillText("Gyro",x0+45,12)}
function renderValidation(){if(V.validation.length<FS*3){status.textContent="复测少于 3 秒，数据不足。";return}const raw={a:hfRms(V.validation,"a"),g:hfRms(V.validation,"g")},filtered={a:hfRms(V.validation,"a",V.profile),g:hfRms(V.validation,"g",V.profile)},A=V.analysis;results.insertAdjacentHTML("beforeend",`<h3 style="margin-top:16px">上机复测</h3><div class="vib-metric"><span>原始加速度，相对初测</span><b class="${raw.a<A.before.a?'vib-good':'vib-warn'}">${raw.a.toFixed(4)} (${(100*raw.a/A.before.a).toFixed(0)}%)</b></div><div class="vib-metric"><span>原始陀螺仪，相对初测</span><b class="${raw.g<A.before.g?'vib-good':'vib-warn'}">${raw.g.toFixed(3)} (${(100*raw.g/A.before.g).toFixed(0)}%)</b></div><div class="vib-metric"><span>复测数据模拟滤波后</span><b>${filtered.a.toFixed(4)} g / ${filtered.g.toFixed(3)} °/s</b></div>`);V.analysis.validation={raw,filtered,samples:V.validation.length};status.textContent="复测分析完成。请比较同转速、同负载下的结果。";update()}
function reset(){Object.assign(V,{phase:"idle",baseline:[],run:[],validation:[],profile:null,analysis:null,lastSeq:null,gaps:0,clipped:0});results.innerHTML='<h3>分析结果</h3><div class="vib-note">分析范围 15–350 Hz。请先完成基线和工况采集。</div>';ctx.clearRect(0,0,canvas.width,canvas.height);status.textContent="请先连接 IMU，保持电机关闭并采集至少 3 秒。";update()}
function exportReport(){const payload={format:"CJ02-vibration-profile-v1",analysis:V.analysis,profile:{notches:Array.from(V.profile),lowpassHz:V.profile.lowpass},captures:{baselineSamples:V.baseline.length,runSamples:V.run.length,validationSamples:V.validation.length,gaps:V.gaps,nearClipping:V.clipped}};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`cj02-vibration-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
B.baseline.onclick=()=>begin("baseline");B.run.onclick=()=>begin("run");B.stop.onclick=stop;B.analyze.onclick=analyze;B.validation.onclick=()=>begin("validation");B.reset.onclick=reset;B.export.onclick=exportReport;update();
})();
